module.exports = {
	DEFAULT_REDIS_PORT: 6379,
	DEFAULT_REDIS_HOST: '127.0.0.1',
	DEFAULT_MYSQL_PORT: 3306,
	DEFAULT_MYSQL_HOST: '127.0.0.1',
	DEFAULT_MYSQL_USE_POOL: false,
	DEFAULT_MYSQL_CONNECT_CB: function() {},

	TYPE_LONG: 'long'
}